### ISSUE TITLE
Scores won't update on cache if played before on party mode

### ISSUE THREAD

**Issue by Elecast2** [motzel/ScoreSaberCountryLeaderboard#98]
**Describe the bug**
If i improve a song that has been previously played on Party mode, the score is updated fine but it wont update on the script, it is shown like if it was played by another player even if the new score is greater than the done on party mode.

**To Reproduce**
1. Play a song on party mode
2. Play the song in solo mode
3. Install ScoreSaberCountryLeaderboard
4. Improve the song in solo mode

**Expected behavior**
The score will be updated sucessfully to scoresaber but ScoreSaberCountryLeaderboard won't update it and still will show the map previous score (for example on the Accuracy vs difficulty graph)

**Screenshots**
![image](https://user-images.githubusercontent.com/23460760/110247378-c38c6e80-7f4a-11eb-966d-772c04effbc0.png)
![image](https://user-images.githubusercontent.com/23460760/110247427-ff273880-7f4a-11eb-89c7-a17617251d8e.png)

**Please complete the following information:**
 - OS: Windows 10
 - Browser Chrome
 - Browser version  89.0.4389.82 (Build oficial) (64 bits)

**Comment by motzel** [comment]
Hi, thanks for a report!

This is very strange. I've never played in party mode, but as far as I know party mode shouldn't send scores at all and have any effect on them. I'll try playing party mode today and then improve the score and see what happens then. It's more likely that it's just a coincidence and ScoreSaber just had problems during the download, because lately the server is often overloaded and doesn't serve data or only gives some of it.

But for problem analysis your data dump would be perfect, could you catch me on Discord at motzel#8017?

**Comment by motzel** [comment]
Yeap, I've played on party mode and score was updated without any problems.
![image](https://user-images.githubusercontent.com/1758707/110316675-555bb080-800b-11eb-94d4-3e9c208a780b.png)

So it's a SS issue probably. As I wrote earlier - catch me on Discord please.

**Comment by Elecast2** [comment]
Thanks for the reply, i just noticed it just happened to me without party mode
![image](https://user-images.githubusercontent.com/23460760/110374293-47b82200-802f-11eb-8e8e-ae533b697d60.png)
is there a way to clear all the cache and set the profile as my profile again? to see if that fixes something

**Comment by Elecast2** [comment]
Elecast#9847, im new to discord, i just sent you a friend request

**Comment by motzel** [comment]
Hi, I've just noticed you reply.

Sure, just either delete DB (F12/Application tab/Indexed DB/select sspl and press delete database button) or force refresh your scores (F12/Console tab/paste "ssplEventBus.publish('refetch-all-player-scores-cmd', 'PLAYER_ID')"/enter). Without quotation marks and replace PLAYER_ID with your player ID (you can take it from URL on SS your profile).

**Comment by motzel** [comment]
Sorry for replying so late, but I have been quite busy with life lately. I've looked through the records in your exported data and it looks like these particular scores are simply not in the database. And since they were downloaded along with those played a few minutes later it's likely that the ScoreSaber API returned incomplete data. It sometimes has problems. There's not much you can do about that except download them again, which you've already done. 

So I am closing this issue, I hope this does not happen to you in the future.
